# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heptapod < Formula
  desc "This is a command line application to manage and fine-tune Time Machine exclude paths."
  homepage "https://github.com/tg44/heptapod"
  version "0.1.9"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tg44/heptapod/releases/download/v0.1.9/heptapod_Darwin_arm64.tar.gz"
      sha256 "39b4c6539ca2cb1247d472a2fb4bb80c5e8c0396a16f55494409e225cada49a4"

      def install
        bin.install "heptapod"
        prefix.install Dir["rules"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tg44/heptapod/releases/download/v0.1.9/heptapod_Darwin_x86_64.tar.gz"
      sha256 "c83fe36e381a64cf0f00f2716cf2f26434552fb086a5e99a3c71c7bf10a660d7"

      def install
        bin.install "heptapod"
        prefix.install Dir["rules"]
      end
    end
  end

  def caveats
    <<~EOS
      Start with `heptapod -h`!
    EOS
  end
end
