# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heptapod < Formula
  desc "This is a command line application to manage and fine-tune Time Machine exclude paths."
  homepage "https://github.com/tg44/heptapod"
  version "0.1.5"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tg44/heptapod/releases/download/v0.1.5/heptapod_0.1.5_Darwin_arm64.tar.gz"
      sha256 "288681b6b009859e144b58ad537f9cbbbdaf0848bb622f69f4172a1f7b76658e"

      def install
        bin.install "heptapod"
        prefix.install Dir["rules"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tg44/heptapod/releases/download/v0.1.5/heptapod_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "9e911d732568993b4c20adeacde42632f573d2790da5102fa7125a150eed20b5"

      def install
        bin.install "heptapod"
        prefix.install Dir["rules"]
      end
    end
  end

  def caveats; <<~EOS
    Start with `heptapod -h`!
  EOS
  end
end
